name: preview
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Nodejs 🎉
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup config ⚙️
        shell: bash
        run: |
          sed -i  's#VITE_PUBLIC_PATH\s*=.*#VITE_PUBLIC_PATH = /Vue3 Vite/#g' ./.env.production
          cat ./.env.production
      - name: Install and Build 🔧
        run: |
          npm i -g pnpm
          pnpm i
          pnpm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
            branch: gh-pages
            folder: dist